CREATE DATABASE DreamScreen CHARACTER SET UTF8 COLLATE utf8_bin;

CREATE TABLE DreamScreen.User(
    id INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY(id)
);

CREATE TABLE DreamScreen.Item(
    id INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
    id_user INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image LONGBLOB NULL,
    accomplished BOOLEAN NOT NULL DEFAULT 0,
    CONSTRAINT PK_Item PRIMARY KEY(id, id_user),
    CONSTRAINT FK_User FOREIGN KEY(id_user) REFERENCES User(id) ON DELETE CASCADE
);